server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://mysql:3306/medical_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        service-name: patient-service