server:
  port: 8085

spring:
  application:
    name: risk-assessment-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        service-name: risk-assessment-service